name: 'dbt_project'
version: '1.0'
profile: 'dbt_project'

model-paths: ["models"]

models:
  dbt_project:
    bronze:
      materialized: view
    silver:
      materialized: view
    gold:
      materialized: table
